### ISSUE TITLE
Str Encoding Error on Python 2.7.13

### ISSUE THREAD

**Issue by shaungehring** [Aula13/poloniex#10]
File "/usr/local/lib/python2.7/site-packages/poloniex/poloniex.py", line 129, in __call__
    bytes(self._secret, 'utf-8'),
TypeError: str() takes at most 1 argument (2 given)

**Comment by calebadcock** [comment]
I changed line 129 from `bytes(self._secret, 'utf-8'),` to `bytes(self._secret),`. The error is gone for now.
