### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by dragosgr2** [Aula13/poloniex#17]
Hi,

Since last week I experienced slow or down APIs with the error Connection Timeout.
Do you see the same thing? Is this a Poloniex issue or mine?

I have a trading bot and it stops because of this issue: trying to retrieve data from Poloniex and get back Connection Timeout error: urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

Do you have an idea how I would pass by this error and let the code run further?

Thanks

**Comment by enricobacis** [comment]
Hi @dragosgr2 , I'd say that this is not an issue with this project, it might be on Poloniex side or your side, something that you can do is to have multiple retries like this:

```
from urllib.error import URLError

retries = 10
while retries:
    try:
        polo.yourmethod(yourargs)
        break
    except URLError as err:
        retries -= 1
        if not retries:
            raise err
```
        
Please close this issue if you can fix the problem like this

**Comment by dnlcrl** [comment]
Hi, I'd wait for some time before trying again, there was a scheduled maintenance today that has to be "short" but it's during more than 16 hs (https://cointelegraph.com/news/poloniex-says-scheduled-wallet-maintenance-to-end-shortly-no-update-16-hrs-after-start)

**Comment by dnlcrl** [comment]
Also this: https://twitter.com/Poloniex/status/971760457655701504
<img width="574" alt="schermata 2018-03-09 alle 11 57 35" src="https://user-images.githubusercontent.com/1212655/37204456-2681a5dc-2391-11e8-8416-b87b719c177d.png">

(no further updates since then)

**Comment by dragosgr2** [comment]
Thank you for the feedback!
It is happening for a week already.
