### ISSUE TITLE
Internal error. Please try again

### ISSUE THREAD

**Issue by ranamalo** [Aula13/poloniex#19]
Getting this error.  Perhaps it should silently retry?:

```
   trade_history_dict_raw = self.polo.returnTradeHistory(currencyPair='all', start=start_date_timestamp, end=end_date_timestamp, limit=10000)

  File "/opt/cryptocurrency_tools/lib/python3.4/site-packages/poloniex/poloniex.py", line 235, in returnTradeHistory

    start=start, end=end, limit=limit)

  File "/opt/cryptocurrency_tools/lib/python3.4/site-packages/poloniex/poloniex.py", line 50, in _fn

    raise PoloniexCommandException(respdata['error'])

poloniex.exceptions.PoloniexCommandException: Internal error. Please try again.
```

**Comment by enricobacis** [comment]
It might be useful for public APIs, I'm not sure that enabling this for private APIs would be a good choice. What's your opinion on this?

**Comment by ranamalo** [comment]
That's a good point.  Agreed for public APIs.  For private APIs seems like it would make sense if the call is readonly, like in this case (returnTradeHistory).  Maybe there's an adverse effect I'm not thinking of?  There could be a default number of tries, and if we hit that default, we raise an exception and give the stack trace.

**Comment by IanQS** [comment]
What version of the API are you running? I ran into a similar error at one point I think but the error went away when I upgrade to 0.0.17 (and now it displays specifically what the error is)

**Comment by enricobacis** [comment]
I'm closing this since it has been 2 years without updates
