### ISSUE TITLE
returnTradeHistoryPublic does NOT work.

### ISSUE THREAD

**Issue by EUA** [Aula13/poloniex#4]
On Arch Linux x86_64
Python 2.7.13
Installed via `sudo pip2 poloniex`

`polo=poloniex.Poloniex( apikey=...,secret=...)`

`polo.returnTradeHistory('ETH_BCH')` works
but
`polo.returnTradeHistoryPublic('ETH_BCH') `does **NOT** work!

**Comment by enricobacis** [comment]
Could you post here the error message?

**Comment by EUA** [comment]
There are no error message.
```
>>> polo = poloniex.Poloniex()
>>> polo.returnTradeHistoryPublic('ETH_BCH')
>>> 
```
Just try and see.
Tried with latest git, same result.
