### ISSUE TITLE
A simple trading tool using your library.

### ISSUE THREAD

**Issue by timucin** [Aula13/poloniex#7]
Hello,

I made a simple trading tool to automate trading and race with the bots on poloniex. Your library is the core component. I'd like to thank you for this library.

https://github.com/timucin/cyripto_trader

Maybe you may want to add a link to your readme showing my tool as an example.
I welcome edits and additions too. That's why I like free software. 

Best Regards,

Tim.

**Comment by enricobacis** [comment]
Thank you Tim for the nice project. I've added the link to our README.
