### ISSUE TITLE
Package poloniex 0.0.10 is broken

### ISSUE THREAD

**Issue by msantl** [Aula13/poloniex#8]
Hi,

installing poloniex with `pip3 install poloniex` installs version 0.0.10. (https://pypi.python.org/pypi/poloniex) which doesn't have [this](https://github.com/Aula13/poloniex/pull/6) pull request.

Can you update the pip package with the latest version?

Thanks in advance.

**Comment by enricobacis** [comment]
thanks for pointing that out. I've uploaded version 0.0.11 on PyPI, it should be fixed now.
