### ISSUE TITLE
polo.returnTicker() execturion shows  JSONDecodeError        

### ISSUE THREAD

**Issue by samueldinesh** [Aula13/poloniex#9]
_from poloniex import Poloniex
polo = Poloniex()
ticker = polo.returnTicker()['BTC_ETH']
print(ticker)_

JSONDecodeError                           Traceback (most recent call last)
<ipython-input-51-846c038806cb> in <module>()
      6 polo = Poloniex('key', 'secret')
      7 
----> 8 ticker = polo.returnTicker()['BTC_ETH']
      9 print(ticker)
     10 

~/miniconda2/envs/cryptocurrency-analysis/lib/python3.6/site-packages/poloniex/poloniex.py in returnTicker(self)
     73     def returnTicker(self):
     74         """Returns the ticker for all markets."""
---> 75         return self._public('returnTicker')
     76 
     77     def return24hVolume(self):

~/miniconda2/envs/cryptocurrency-analysis/lib/python3.6/site-packages/poloniex/poloniex.py in _fn(self, command, **params)
     37 
     38         self.semaphore.acquire()
---> 39         resp = fn(self, command, **params).json(object_hook=_AutoCastDict)
     40         if 'error' in resp:
     41             raise PoloniexCommandException(resp['error'])

~/miniconda2/envs/cryptocurrency-analysis/lib/python3.6/site-packages/requests/models.py in json(self, **kwargs)
    883                     # used.
    884                     pass
--> 885         return complexjson.loads(self.text, **kwargs)
    886 
    887     @property

~/miniconda2/envs/cryptocurrency-analysis/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    365     if parse_constant is not None:
    366         kw['parse_constant'] = parse_constant
--> 367     return cls(**kw).decode(s)

~/miniconda2/envs/cryptocurrency-analysis/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

~/miniconda2/envs/cryptocurrency-analysis/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [ ]:
￼
​
**What is this error please  explain.....**
And for every time i try to use different poloniex api it shows only error...
Why this is happening.... on poloniex api...

**Comment by enricobacis** [comment]
Well.. I'm pretty sure you have problem with all poloniex APIs because the problem is in your setup. I can't reproduce the bug you are describing as you can see here:

https://asciinema.org/a/jXMZp4GMSNqVnD1hVl6ztLNk5

Feel free to open again this issue if you think it is related to this package.

**Comment by bmabsout** [comment]
The issue happened to me, turns out the request was returning a 403 error because in some regions a captcha shows up causing the error. One can run the captcha in the browser, put the cookie in the header of the request (which expires around an hour after creation) and run it. Or use a vpn

**Comment by enricobacis** [comment]
Since these types of problems were affecting more users, I decided to check for HTTP error codes early, so that the exceptions that are thrown are more intelligible. If you try version 0.0.13 now and cause the same error, you should get an HTTPError specifying the 403 access problem, which is much more readable.

**Comment by samueldinesh** [comment]
Ok thank you
